'''
For explanation of this type checking "Abstract class" look up wikipage:

    DevOps --> Wiki --> NQCP-teams --> Characterization-team --> Onboarding-to-Characterization --> Photonic Characterization Structures

'''
from typing import Protocol
from photonicdrivers.Abstract.Connectable import Connectable

class Thorlabs_Power_Meter_Driver(Connectable, Protocol):


    def get_power(self) -> float: ...

    def set_wavelength(self, wavelength_nm: float): ...

    def set_auto_range(self, auto_range_bool: bool): ...

    def get_wavelength(self) -> float: ...

    def set_averaging(self, average: int): ...

    def get_averaging(self) -> int: ...

    def get_power_unit(self) -> str: ...

    def set_power_unit(self, power_unit: str): ...

    def set_beam(self, beam): ...

    def reset(self): ...

    def zero(self): ...