from photonicdrivers.Kuhlmobil.VdHB400_Driver import VdHB400_Driver

driver = VdHB400_Driver("COM4")
driver.connect()
print("get_power_status: ", driver.get_power_status())
print("get_pump1_status: ", driver.get_pump1_status())
print("get_pump2_status: ", driver.get_pump1_status())
print("get_control_status: ", driver.get_control_status())
print("get_temperature_pt1: ", driver.get_temperature_pt1())
print("get_temperature_pt2: ", driver.get_temperature_pt2())
print("get_temperature_pt3: ", driver.get_temperature_pt3())
print("get_temperature_pt4: ", driver.get_temperature_pt4())
print("get_setpoint_temperature: ", driver.get_setpoint_temperature())
print("get_display_software_version: ", driver.get_display_software_version())
print("get_control_software_version: ", driver.get_control_software_version())
print("get_flow_rate_df1: ", driver.get_flow_rate_df1())
print("get_flow_rate_df2: ", driver.get_flow_rate_df2())
print("get_analog_input_output1: ", driver.get_analog_input_output1())
print("get_analog_input_output2: ", driver.get_analog_input_output2())
print("get_analog_input_output3: ", driver.get_analog_input_output3())
print("get_analog_input_output4: ", driver.get_analog_input_output4())
print("get_error_status: ", driver.get_error_status())
driver.disconnect()
