name: Run mypy and pytest


on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
  merge_group:
    branches: ['master']

jobs:
  pytestmypy:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"] # ["3.9", "3.10", "3.11"]
        exclude:
          - os: windows-latest
            python-version: "3.9"
          - os: windows-latest
            python-version: "3.11"
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v3.5.3
      with:
        submodules: true
        # we need full history with tags for the version number
        fetch-depth: '0'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.3.1
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          pyproject.toml
    - name: upgrade pip setuptools wheel
      run: python -m pip install --upgrade pip setuptools wheel
      shell: bash
    - name: install photonicdrivers
      run: |
        pip install .[ci]
    - name: Test with pytest
      run: |
        pytest ./photonicdrivers/tests/
